version: "3.8"

services:
  fastapi:
      build: ./fastapi
      container_name: fastapi
      volumes:
        - .:/usr/scr/app
      ports:
        - "8000:8000"
      depends_on:
        - pgdb
  pgdb:
    image: postgres:alpine
    container_name: pgdb
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=fastapi_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

